version: '2'
services: 
  api:
    build: .
    ports:
      - 8080:8080
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:latest
    ports:
      - 6379:6379